using Godot;
using Godot.Collections;

namespace Mutigsoft.PrettyDunGen3D;

[Tool]
public partial class PrettyDunGen3DChunk : Node3D
{
    public Vector3I Coordinates =>
        Generator != null ? Generator.GetChunkCoordinate(Position) : Vector3I.Zero;
    public Vector3 Size =>
        Generator != null ? ((Vector3)Vector3.One) * Generator.chunkSize : Vector3.Zero;
    public Array<string> Categories => categories;

    [Export]
    private Array<string> categories = new();

    [Export]
    public PrettyDunGen3DGenerator Generator { get; private set; }

    public PrettyDunGen3DChunk(PrettyDunGen3DGenerator generator)
    {
        Generator = generator;
    }

    // Default Constructor should not be used. The Node is generated by PrettyDunGen3DGenerator
    // Just here to provide a way for Godot to create this Node (Im unsure if this is needed though).
    public PrettyDunGen3DChunk() { }

    MeshInstance3D debugMeshInstance3D;

    // TODO  use a Timer instead?
    public override void _PhysicsProcess(double delta)
    {
        if (Engine.IsEditorHint())
            DrawDebug();
    }

    public bool AddCategory(string category)
    {
        if (categories.Contains(category))
            return false;

        categories.Add(category);
        Generator.InformChunkCategoryChanged(this);
        return true;
    }

    public bool ContainsCategory(string category) => categories.Contains(category);

    public bool RemoveCategory(string category)
    {
        if (categories.Remove(category))
        {
            Generator.InformChunkCategoryChanged(this);
            return true;
        }
        return false;
    }

    public void DrawDebug()
    {
        if (Generator.ShowDebug)
        {
            DebugDraw3D.ScopedConfig().SetThickness(0.2f);
            DebugDraw3D.DrawBox(
                GlobalPosition,
                Quaternion.Identity,
                Size,
                Generator.ChunkDebugColor,
                true
            );
        }
    }
}
