using Godot;
using Godot.Collections;

namespace PrettyDunGen3D;

// TODO Create better Property Hints (GetPropertyList)
// TODO Create Path Debugging in Here
// TODO Add a shortcut to know what neighbours this chunk has
// TODO Add Color Coding for Debugging (Basically rules can overwrite the color of the chunk / edge)

[Tool]
public partial class PrettyDunGen3DChunk : Node3D
{
    public Vector3I Coordinates { get; private set; }
    public Vector3 Size { get; set; }
    public Array<string> Categories => categories;
    public PrettyDunGen3DGenerator Generator { get; private set; }

    [Export]
    private Array<string> categories = new();

    public PrettyDunGen3DChunk(PrettyDunGen3DGenerator generator, Vector3I coordinates)
    {
        Generator = generator;
        Coordinates = coordinates;
    }

    // Default Constructor should not be used. The Node is generated by PrettyDunGen3DGenerator
    // Just here to provide a way for Godot to create this Node (Im unsure if this is needed though).
    public PrettyDunGen3DChunk() { }

    MeshInstance3D debugMeshInstance3D;

    // TODO  use a Timer instead?
    public override void _PhysicsProcess(double delta)
    {
        if (Engine.IsEditorHint())
            DrawDebug();
    }

    public bool AddCategory(string category)
    {
        if (categories.Contains(category))
            return false;

        categories.Add(category);
        Generator.InformChunkCategoryChanged(this);
        return true;
    }

    public bool ContainsCategory(string category) => categories.Contains(category);

    public bool RemoveCategory(string category)
    {
        if (categories.Remove(category))
        {
            Generator.InformChunkCategoryChanged(this);
            return true;
        }
        return false;
    }

    public void DrawDebug()
    {
        if (Generator.ShowDebug)
        {
            DebugDraw3D.ScopedConfig().SetThickness(0.2f);
            DebugDraw3D.DrawBox(
                GlobalPosition,
                Quaternion.Identity,
                Size,
                Generator.ChunkDebugColor,
                true
            );
        }
    }
}
